---
#
# Static website
#
apiVersion: v1
kind: Service
metadata:
  name: coalitions
spec:
  ports:
  - port: 80
  selector:
    app: coalitions
  type: NodePort
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: coalitions
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: coalitions
    spec:
      containers:
      - name: coalitions
        image: andimiller/coalitions
        ports:
        - containerPort: 80
          protocol: "TCP"
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 15
          timeoutSeconds: 1
---
#
# Routing
#
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: coalitions-tls
  annotations:
    kubernetes.io/tls-acme: "true"
    kubernetes.io/ingress.class: "nginx"
spec:
  tls:
  - hosts:
    - coalitions.inyour.space
    secretName: coalitions-tls
  rules:
  - host: coalitions.inyour.space
    http:
      paths:
      - path: /
        backend:
          serviceName: coalitions
          servicePort: 80

---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: coalitions
  annotations:
    # kubernetes.io/tls-acme: "true"
    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
  - host: coalitions.inyour.space
    http:
      paths:
      - path: /
        backend:
          serviceName: coalitions
          servicePort: 80
